# Generated by Django 5.2.4 on 2025-08-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
